# Generated by Django 5.2.14 on 2026-09-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('placeholder', 'Placeholder (no media yet)')], default='image', max_length=11),
        ),
    ]
