# Generated by Django 5.2.14 on 2026-09-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='og_image',
            field=models.CharField(blank=True, help_text='Custom Open Graph image (1200x630). Falls back to thumbnail.', max_length=255, null=True),
        ),
    ]
